### ISSUE TITLE
通过magisk无法刷入

### ISSUE THREAD

**Issue by zhjnerv** [Magisk-Modules-Alt-Repo/gboard-dict-3#3]
显示请检查是否安装Gboard
系统miui13 A12
Gboard 版本 116.10.433184565

**Comment by entr0pia** [comment]
和 Gboard 版本无关

1. Fox Manager 似乎无法访问 `/data/data` 目录, 尝试从 [Release](https://github.com/entr0pia/gboard_dict_3/releases/tag/v2.1.1) 页面下载模块, 使用官方 Magisk Manager 安装;
2. 在 `adb shell` 中, 以root权限执行以下两条命令, 回复返回的结果:
    - `ls -n /data/data | grep "com.google.android.inputmethod.latin" | awk '{print $3}'`
    -  `dumpsys package com.google.android.inputmethod.latin | grep userId | sed '$d;s/[^0-9]//g'`

**Comment by zhjnerv** [comment]
尝试通过 release 页面下载的文件，刷入成功了。
